<a href="https://colab.research.google.com/github/SravyaSri123/AIML-batch-5/blob/main/assignment%202-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def misplaced_tiles(puzzle, goal):
    # Calculate the number of misplaced tiles, ignoring the blank space
    return np.sum(np.where(puzzle != goal, 1, 0)) - 1

def get_neighbors(puzzle):
    # Function to get the neighbors (successors) of the current state
    neighbors = []
    blank_pos = np.where(puzzle == 0)[0][0]
    row, col = divmod(blank_pos, 3)

    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # Up, Down, Left, Right
    for dr, dc in moves:
        new_row, new_col = row + dr, col + dc
        if 0 <= new_row < 3 and 0 <= new_col < 3:
            new_blank_pos = new_row * 3 + new_col
            new_puzzle = puzzle.copy()
            new_puzzle[blank_pos], new_puzzle[new_blank_pos] = new_puzzle[new_blank_pos], new_puzzle[blank_pos]
            neighbors.append(new_puzzle)
    return neighbors

def a_star_8_puzzle(initial_state, goal_state):
    # Initial state setup with g(n)=0 and h(n) using the misplaced_tiles heuristic
    state = [{'puzzle': initial_state, 'parent': None, 'gn': 0, 'hn': misplaced_tiles(initial_state, goal_state)}]
    explored = []

    while state:
        # Sort the states by f(n) = g(n) + h(n) and pop the first
        state.sort(key=lambda x: x['gn'] + x['hn'])
        current = state.pop(0)
        explored.append(current['puzzle'].tobytes())

        if np.array_equal(current['puzzle'], goal_state):
            # Goal state reached, reconstruct and return the path
            return reconstruct_path(current, explored)

        for neighbor in get_neighbors(current['puzzle']):
            if neighbor.tobytes() not in explored:
                gn = current['gn'] + 1  # Cost from start to node
                hn = misplaced_tiles(neighbor, goal_state)  # Heuristic cost
                state.append({'puzzle': neighbor, 'parent': current, 'gn': gn, 'hn': hn})

def reconstruct_path(node, explored):
    path = []
    while node['parent'] is not None:
        path.append(node['puzzle'])
        node = node['parent']
    path.append(node['puzzle'])  # Add the initial state
    return path[::-1]  # Return reversed path

# Example usage
initial_state = np.array([2, 8, 3, 1, 6, 4, 7, 0, 5])
goal_state = np.array([1, 2, 3, 8, 0, 4, 7, 6, 5])

solution_path = a_star_8_puzzle(initial_state, goal_state)
print("Solution Path:")
for step, state in enumerate(solution_path):
    print(f"Step {step}:\n{state.reshape(3, 3)}\n")

print(f"Total moves: {len(solution_path) - 1}")

Solution Path:
Step 0:
[[2 8 3]
 [1 6 4]
 [7 0 5]]

Step 1:
[[2 8 3]
 [1 0 4]
 [7 6 5]]

Step 2:
[[2 0 3]
 [1 8 4]
 [7 6 5]]

Step 3:
[[0 2 3]
 [1 8 4]
 [7 6 5]]

Step 4:
[[1 2 3]
 [0 8 4]
 [7 6 5]]

Step 5:
[[1 2 3]
 [8 0 4]
 [7 6 5]]

Total moves: 5
